curl -O https://cs61c.org/su24/pdfs/discussions/disc01.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc01-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc02.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc02-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc03.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc03-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc04.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc04-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc05.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc05-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc06.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc06-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc07.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc07-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc08.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc08-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc09.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc09-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc10.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc10-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc11.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc11-sols.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc12.pdf
curl -O https://cs61c.org/su24/pdfs/discussions/disc12-sols.pdf
